name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: slef-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
